name: CI # Give your workflow a name

on: 
  push: # Run workflow on every push
    branches: [ main ] # Test code before merging
  # pull_request:
  #   branches: [ main ] 

jobs: # Define the jobs (tasks) the workflow will perform
  build:
    runs-on: ubuntu-latest # Specify the OS to run the job on
    steps: # Steps inside this job
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '22.x'

    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: CI=false npm run build

    # - name: Run Unit Tests and generate coverage report # Execute code
    #   uses: npm run test.coverage


    

    


